{% set name = "django-cors-headers" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a971cd4c75b29974068cc36b5c595698822f1e0edd5f1b32ea42ea37326ad4aa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - django >=2.2

  run:
    - python >=3.6
    - django >=2.2

test:
  imports:
    - corsheaders

about:
  home: https://github.com/ottoyiu/django-cors-headers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Django app for handling the server headers required for Cross-Origin Resource Sharing (CORS)

  description: |
    A Django App that adds CORS (Cross-Origin Resource Sharing) headers to responses.

    Although JSON-P is useful, it is strictly limited to GET requests. 
    CORS builds on top of XmlHttpRequest to allow developers to make cross-domain requests, 
    similar to same-domain requests. Read more about it here <http://www.html5rocks.com/en/tutorials/cors/>.

  dev_url: https://github.com/ottoyiu/django-cors-headers

extra:
  recipe-maintainers:
    - rxm7706
    - lsetiawan
    - timsnyder
    - MichelML
